config/routes.rb
Rails.application.routes.draw do
  resources :mining_types
  get 'welcome/index'
  resources :coins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coin.rb
class Coin < ApplicationRecord
  belongs_to :mining_type, class_name: 'MiningType', foreign_key: 'mining_type_id'
end

app/models/mining_type.rb
class MiningType < ApplicationRecord
  has_many :coins
end

app/controllers/application_controller.rb
# Define all behavior that will happen through all application
class ApplicationController < ActionController::Base
  before_action :set_locale

  def set_locale
    cookies[:locale] = params[:locale] if params[:locale]

    I18n.locale = cookies[:locale] if cookies[:locale] && I18n.locale != cookies[:locale]
  end
end

app/controllers/coins_controller.rb
# Controls pages behaviors relatives to coins.
class CoinsController < ApplicationController
  # layout 'adm'

  before_action :set_coin, only: %i[show edit update destroy]
  before_action :set_mining_type_options, except: %i[show destroy]

  # GET /coins
  # GET /coins.json
  def index
    @coins = Coin.all
    cookies[:coins_page_last_access_in] = l DateTime.now
  end

  # GET /coins/1
  # GET /coins/1.json
  def show; end

  # GET /coins/new
  def new
    @coin = Coin.new
  end

  # GET /coins/1/edit
  def edit; end

  # POST /coins
  # POST /coins.json
  def create
    @coin = Coin.new(coin_params)

    respond_to do |format|
      if @coin.save
        format.html { redirect_to @coin, notice: 'Coin was successfully created.' }
        format.json { render :show, status: :created, location: @coin }
      else
        format.html { render :new }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coins/1
  # PATCH/PUT /coins/1.json
  def update
    respond_to do |format|
      if @coin.update(coin_params)
        format.html { redirect_to @coin, notice: 'Coin was successfully updated.' }
        format.json { render :show, status: :ok, location: @coin }
      else
        format.html { render :edit }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coins/1
  # DELETE /coins/1.json
  def destroy
    @coin.destroy
    respond_to do |format|
      format.html { redirect_to coins_url, notice: 'Coin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_coin
    @coin = Coin.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def coin_params
    params.require(:coin).permit(:coin_name, :acronym, :image_url, :mining_type_id)
  end

  def set_mining_type_options
    @mining_types_options = MiningType.all.pluck(:type_name, :id)
  end
end

app/controllers/mining_types_controller.rb
class MiningTypesController < ApplicationController
  before_action :set_mining_type, only: %i[ show edit update destroy ]

  # GET /mining_types or /mining_types.json
  def index
    @mining_types = MiningType.all
    session[:mining_type_page_last_request_in] = l DateTime.now
  end

  # GET /mining_types/1 or /mining_types/1.json
  def show; end

  # GET /mining_types/new
  def new
    @mining_type = MiningType.new
  end

  # GET /mining_types/1/edit
  def edit; end

  # POST /mining_types or /mining_types.json
  def create
    @mining_type = MiningType.new(mining_type_params)

    respond_to do |format|
      if @mining_type.save
        format.html { redirect_to @mining_type, notice: 'Mining type was successfully created.' }
        format.json { render :show, status: :created, location: @mining_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mining_types/1 or /mining_types/1.json
  def update
    respond_to do |format|
      if @mining_type.update(mining_type_params)
        format.html { redirect_to @mining_type, notice: "Mining type was successfully updated." }
        format.json { render :show, status: :ok, location: @mining_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mining_types/1 or /mining_types/1.json
  def destroy
    @mining_type.destroy
    respond_to do |format|
      format.html { redirect_to mining_types_url, notice: "Mining type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mining_type
      @mining_type = MiningType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mining_type_params
      params.require(:mining_type).permit(:type_name, :acronym)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @teacher = 'Jackson Pires'
    @course = params[:curso] || 'Ruby on Rails 5.2 - do início ao fim'
    @coins = Coin.all
    @mining_types = MiningType.all
  end
end

app/helpers/application_helper.rb
# Methods to help rendering infos to share with entire application
module ApplicationHelper; end

app/helpers/coins_helper.rb
module CoinsHelper
end

app/helpers/mining_types_helper.rb
module MiningTypesHelper
end

app/helpers/welcome_helper.rb
# Methods to help rendering infos in welcome view
module WelcomeHelper
  def format_date_br(us_date_format)
    us_date_format.strftime('%d/%m/%Y')
  end

  def rails_environment
    environments = {
      production: 'produção',
      development: 'desenvolvimento',
      test: 'teste',
      staging: 'homologação'
    }

    environments[Rails.env.to_sym]
  end
end

app/views/coins/_form.html.erb
<%= form_with(model: coin, local: true) do |form| %>
  <% if coin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(coin.errors.count, "error") %> prohibited this coin from being saved:</h2>

      <ul>
      <% coin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :coin_name %>
    <%= form.text_field :coin_name, class: "form-control", placeholder: "Bitcoin" %>
  </div>

  <div class="form-group">
    <%= form.label :acronym %>
    <%= form.text_field :acronym, class: "form-control", placeholder: "BTC" %>
  </div>

  <div class="form-group">
    <%= form.label :image_url %>
    <%= image_tag coin.image_url, width: 25, height: 25 if coin.image_url != nil %>
    <br>
    <%= form.text_field :image_url, class: "form-control", placeholder: "https://img.ur/bitcoin.png" %>
  </div>

  <div class="form-group">
    <%= form.label :mining_type_id %>
    <%= form.select(:mining_type_id, @mining_types_options, { include_blank: t('options.select') }, class: "form-control") %>
  </div>

  <div class="actions mb-3">
    <%= form.submit nil, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/coins/edit.html.erb
<h1><%= t 'editing' %> <%= t @coin.model_name.human %></h1>

<%= render 'form', coin: @coin %>

<%= link_to t('links.show'), @coin, class: "btn btn-outline-primary" %>
<%= link_to t('links.go_back'), coins_path, class: "btn btn-outline-secondary" %>

app/views/coins/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @coins.model_name.human(count: @coins.count) %></h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th><%= @coins.human_attribute_name(:coin_name) %></th>
      <th><%= @coins.human_attribute_name(:acronym) %></th>
      <th><%= @coins.human_attribute_name(:image_url) %></th>
      <th colspan="3">Ações</th>
    </tr>
  </thead>

  <tbody>
    <% @coins.each do |coin| %>
      <tr>
        <td><%= coin.coin_name %></td>
        <td><%= coin.acronym %></td>
        <td>
          <%= image_tag coin.image_url, size: "25x25" if coin.image_url != nil %>
        </td>
        <td><%= link_to t('links.show'), coin %></td>
        <td><%= link_to t('links.edit'), edit_coin_path(coin) %></td>
        <td>
          <%= link_to t('links.delete'), coin, method: :delete, data: { confirm: "#{t 'messages.confirm'}" } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "#{t 'links.add_new'} #{@coins.model_name.human}", new_coin_path, class: "btn btn-primary" %>

app/views/coins/new.html.erb
<h1><%= t 'adding' %> <%= t @coin.model_name.human %></h1>

<%= render 'form', coin: @coin %>

<%= link_to t('links.go_back'), coins_path, class: "btn btn-outline-secondary" %>

app/views/coins/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t 'showing' %> <%= t @coin.model_name.human %></h1>

<form>
  <div class="form-group">
    <%= label_tag nil, @coin.class.human_attribute_name(:coin_name) %>
    <%= text_field_tag nil, @coin.coin_name, class: "form-control", disabled: true %>
  </div>

  <div class="form-group">
    <%= label_tag nil, @coin.class.human_attribute_name(:acronym) %>
    <%= text_field_tag nil, @coin.acronym, class: "form-control", disabled: true %>
  </div>

  <div class="form-group">
    <%= label_tag nil, @coin.class.human_attribute_name(:image_url) %>
    <%= image_tag @coin.image_url, width: 25, height: 25 if @coin.image_url != nil %>
    <br>
    <%= text_field_tag nil, @coin.class.human_attribute_name(:image_url), class: "form-control", disabled: true %>
  </div>

  <div class="form-group">
    <%= label_tag nil, @coin.class.human_attribute_name(:mining_type) %>
    <%= text_field_tag nil, @coin.mining_type.type_name, class: "form-control", disabled: true %>
  </div>

</form>

<%= link_to t('links.edit'), edit_coin_path(@coin), class: "btn btn-primary" %>
<%= link_to t('links.go_back'), coins_path, class: "btn btn-secondary" %>

app/views/layouts/adm.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CryptoWallet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>CABEÇALHO - ADM</h1>
    <%= yield %>
    <h1>RODAPÉ - ADM</h1>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CryptoWallet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag params[:controller], media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <ul class="nav justify-content-end">
        <li class="nav-item">
          <%= link_to '[HOME]', root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Português', '?locale=pt-BR', class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'English', '?locale=en', class: "nav-link" %>
        </li>
      </ul>
      <%= yield %>
    </div>

    <%= javascript_include_tag params[:controller], 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/mining_types/_form.html.erb
<%= form_with(model: mining_type, local: true) do |form| %>
  <% if mining_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mining_type.errors.count, "error") %> prohibited this mining_type from being saved:</h2>

      <ul>
      <% mining_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :type_name %>
    <%= form.text_field :type_name, class: "form-control", placeholder: "Proof of Work" %>
  </div>

  <div class="form-group">
    <%= form.label :acronym %>
    <%= form.text_field :acronym, class: "form-control", placeholder: "PoW" %>
  </div>

  <div class="actions mb-3">
    <%= form.submit nil, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/mining_types/edit.html.erb
<h1><%= t 'editing' %> <%= t @mining_type.model_name.human %></h1>

<%= render 'form', mining_type: @mining_type %>

<%= link_to t('links.show'), @mining_type, class: "btn btn-outline-primary" %>
<%= link_to t('links.go_back'), mining_types_path, class: "btn btn-outline-secondary" %>

app/views/mining_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @mining_types.model_name.human(count: @mining_types.count) %></h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th><%= @mining_types.human_attribute_name(:type_name) %></th>
      <th><%= @mining_types.human_attribute_name(:acronym) %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mining_types.each do |mining_type| %>
      <tr>
        <td><%= mining_type.type_name %></td>
        <td><%= mining_type.acronym %></td>
        <td><%= link_to t('links.show'), mining_type %></td>
        <td><%= link_to t('links.edit'), edit_mining_type_path(mining_type) %></td>
        <td>
          <%= link_to t('links.delete'), mining_type, method: :delete, data: { confirm: "#{t 'messages.confirm'}" } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "#{t 'links.add_new_male'} #{@mining_types.model_name.human}", new_mining_type_path, class: "btn btn-primary" %>

app/views/mining_types/new.html.erb
<h1><%= t 'adding' %> <%= t @mining_type.model_name.human %></h1>

<%= render 'form', mining_type: @mining_type %>

<%= link_to t('links.go_back'), mining_types_path, class: "btn btn-outline-secondary" %>

app/views/mining_types/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t 'showing' %> <%= t @mining_type.model_name.human %></h1>

<form>
  <div class="form-group">
    <%= label_tag nil, @mining_type.class.human_attribute_name(:type_name) %>
    <%= text_field_tag nil, @mining_type.type_name, class: "form-control", disabled: true %>
  </div>

  <div class="form-group">
    <%= label_tag nil, @mining_type.class.human_attribute_name(:acronym) %>
    <%= text_field_tag nil, @mining_type.acronym, class: "form-control", disabled: true %>
  </div>

</form>


<p>
  <%= link_to t('links.edit'), edit_mining_type_path(@mining_type), class: "btn btn-primary" %>
  <%= link_to t('links.go_back'), mining_types_path, class: "btn btn-secondary" %>
</p>

app/views/welcome/_menu.html.erb
<%= link_to "#{@coins.model_name.human(count: @coins.count)}", coins_path, class: "btn btn-primary btn-lg", role: "button" %>
<%= link_to "#{@mining_types.model_name.human(count: @mining_types.count)}", mining_types_path, class: "btn btn-primary btn-lg", role: "button" %>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1 class="display-4">
    <%= t 'greetings' %>
  </h1>
  <p class="lead"><%= t 'messages.welcome_app_description' %></p>
  <hr class="my-4">
  <p><%= t 'messages.welcome_choose_option' %></p>
  <p class="lead">
    <%= render 'menu' %>
  </p>
</div>

<%# TODO: Colocar um botão para ocultar todo o conteúdo abaixo e só exibir quando for clicado. Pode ser no estilo accordion %>
<div class="ruby-references">
  <p>Alguns exemplos de como usar o ERB</p>
  <h2>Usando código Ruby no HTML com ERB</h2>
  <% name = 'Jean' %>
  <h3>Olá, <%= name %>!</h3> 
  <p>Seu nome ao contrário é <%= name.reverse.downcase.capitalize %></p>
  <hr />

  <h2>Formatação de data</h2>
  <p><strong>Através do uso de um helper:</strong> A data de hoje é: <%= format_date_br Date.today %></p>
  <p><strong>Através do uso do método <code>I18n.l()</code>:</strong> <%= l Date.today%></p>
  <hr />

  <h2>Verificando o idioma que está definido como padrão</h2>
  <p>O idioma padrão dessa aplicação é o <strong><%= t 'using_language' %></strong>.</p>
  <hr />

  <h2>Verificando ambiente Rails em conjunto de helpers</h2>
  <p>Você está em ambiente de <strong><%= rails_environment %></strong></p>
  <hr />

  <h2>Variáveis de instância/sessão</h2>
  <p>
    Este é o curso <strong><%= @course %></strong>, ministrado pelo professor <strong><%= @teacher %></strong>.
  </p>
  <hr />

  <h2>Acessando dados armazenados em cookies e session</h2>
  <p>
  <% if cookies[:coins_page_last_access_in]%>
    <strong>Data do último acesso à página de Moedas:</strong> <%= cookies[:coins_page_last_access_in] %>
  <% else %>
    <strong>Não há registro de acesso à página de Moedas</strong>
  <% end %>
  </p>
  <p>
  <% if session[:mining_type_page_last_request_in] %>
    <strong>Data da última requisição dos Tipos de mineração:</strong> <%= session[:mining_type_page_last_request_in] %>
  <% else %>
    <strong>Não há registro de requisição aos Tipos de mineração</strong>
  <% end %>
  </p>
  <hr />
</div>